import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import type { Abi } from "viem";

// viem's contract helpers infer function names, argument tuples, return types,
// and event args from literal `as const` ABI values. When TypeScript imports
// artifact JSON through `resolveJsonModule`, the ABI is widened to generic JSON
// shapes, so that inference is lost and callers fall back to broad `Abi` types.
// This postinstall generator copies the artifact ABIs into a TypeScript module
// with `as const satisfies Abi`, keeping boltz-core JSON as the source of truth
// while preserving viem's useful type inference in application code.

type ContractConfig = {
    exportName: string;
    artifactPath: string;
};

type Artifact = {
    abi?: unknown;
};

const contracts: readonly ContractConfig[] = [
    {
        exportName: "erc20Abi",
        artifactPath: "node_modules/boltz-core/out/ERC20.sol/ERC20.json",
    },
    {
        exportName: "etherSwapAbi",
        artifactPath:
            "node_modules/boltz-core/out/EtherSwap.sol/EtherSwap.json",
    },
    {
        exportName: "erc20SwapAbi",
        artifactPath:
            "node_modules/boltz-core/out/ERC20Swap.sol/ERC20Swap.json",
    },
    {
        exportName: "routerAbi",
        artifactPath: "node_modules/boltz-core/out/Router.sol/Router.json",
    },
];

const outputPath = "src/generated/evm-abis.ts";

const readArtifactAbi = (artifactPath: string): Abi => {
    const artifact = JSON.parse(readFileSync(artifactPath, "utf8")) as Artifact;

    if (!Array.isArray(artifact.abi)) {
        throw new Error(`missing ABI array in ${artifactPath}`);
    }

    return artifact.abi as Abi;
};

const generatedExports = contracts
    .map((contract) => {
        const abi = readArtifactAbi(contract.artifactPath);
        return `export const ${contract.exportName} = ${JSON.stringify(abi, null, 4)} as const satisfies Abi;`;
    })
    .join("\n\n");

const output = `import type { Abi } from "viem";

// Generated by scripts/generate-evm-abis.ts. Do not edit by hand.

${generatedExports}
`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(join(process.cwd(), outputPath), output);
