# Simple workflow for deploying static content to GitHub Pages
name: Deploy

on:
  # only run if CI successful
  workflow_run:
    workflows: ["CI"]  # Name of the upstream workflow
    types:
      - completed
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  attestations: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Deploy testnet
  testnet:
    # Only run if CI was successful and the branch is 'test'
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/test' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository dispatch in testnet
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.REPO_TESTNET_TOKEN }}" \
            https://api.github.com/repos/SwapMarket/testnet/dispatches \
            -d '{"event_type":"triggered_from_mainnet"}'

  # Deploy beta
  beta:
    # Only run if CI was successful and the branch is 'test'
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/test' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository dispatch in beta
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.REPO_TESTNET_TOKEN }}" \
            https://api.github.com/repos/SwapMarket/beta/dispatches \
            -d '{"event_type":"triggered_from_mainnet"}'

  # Deploy mainnet
  deploy:
    # Only run if CI was successful and the branch is main
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Copy config
        run: npm run mainnet

      - name: Build
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Attest build provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: '${{ github.workspace }}/dist'

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist folder
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
