import { hex } from "@scure/base";
import { BridgeKind, SwapPosition, SwapType } from "boltz-swaps/types";
import { beforeEach, vi } from "vitest";

import {
    type SwapMetadataPayload,
    buildSwapMetadataPayloadFromSwap,
    decryptSwapMetadata,
    encryptSwapMetadata,
    patchEncryptedSwapMetadata,
} from "../../src/utils/swapMetadata";

const mocks = vi.hoisted(() => ({
    patchSwapMetadata: vi.fn(),
}));

vi.mock("boltz-swaps/client", () => ({
    patchSwapMetadata: mocks.patchSwapMetadata,
}));

const mnemonic =
    "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about";
const otherMnemonic =
    "legal winner thank year wave sausage worth useful legal winner thank yellow";

// Matches the backend's metadata format (hex).
const backendMetadataRegex = /^(?:[0-9a-fA-F]{2})+$/;
const rescueFile = { mnemonic } as never;

const swapId = "swap-id";

const samplePayload: SwapMetadataPayload = {
    dex: {
        hops: [{ type: SwapType.Dex, from: "TBTC", to: "WBTC" }],
        position: SwapPosition.Post,
        quoteAmount: 12345,
    },
    lockupTx: "0xlockup",
    commitmentLockupTxHash: "0xcommitment",
    bridge: {
        sourceAsset: "USDC",
        destinationAsset: "USDC-BASE",
        kind: BridgeKind.Cctp,
        position: SwapPosition.Post,
    },
};

// Payloads carrying a lockup transaction must be bound to their swap.
const boundPayload = { ...samplePayload, swapId };

// Encryption of `boundPayload` with `mnemonic`, generated by the code this
// spec tests. Pins the wire format: HKDF salt/info, AES-GCM, IV length, the
// hex envelope and the payload schema. If this test breaks, every metadata
// blob already stored on the backend becomes undecryptable — never
// regenerate this vector to make a failing test pass; fix the code so old
// blobs keep decrypting.
const goldenVector =
    "47e98dc81b988787e1bee38613eda55c3b34fe116dae7d70dc546c593e21f0817947eae8" +
    "04bf95e26e838aa1d6f2ca87052ecbb05702dad1337b6d0216d899d764a6c53650eda4a1" +
    "29c17263293f89f5522a0f92b461ad7aec127b2b3b9870b6213d99c6a190c3a7cd1b7f4b" +
    "ce970955241dce29540497cd0e2684703510bf97f6b8f7440b7cc21fc1e9b82a2bda5873" +
    "7a305e5f0d20879b5ff5d756bea144ff0037d54b0dcf1d8caa372e4d33a5b6d5b7fa39bb" +
    "c3ff0e779540983f637629d1d1044c012c764526dcc2823c7091011d265b6f38d6c8b31b" +
    "f94486829a310d088656b9c5261a81189f46b5bb3a6b04373cf652c12fe46e7766a42326" +
    "4a3641a61d2b77b728de8686f01f3f80515459433c9af3f3a54667e398e671c03ae43860" +
    "05e8827f0e1112727625ff94ac";

describe("swapMetadata crypto", () => {
    test("round-trips a payload through encrypt/decrypt", async () => {
        const metadata = await encryptSwapMetadata(mnemonic, boundPayload);
        expect(typeof metadata).toBe("string");

        const decrypted = await decryptSwapMetadata(mnemonic, swapId, metadata);
        expect(decrypted).toEqual(samplePayload);
    });

    test("decrypts the golden vector (wire format is frozen)", async () => {
        await expect(
            decryptSwapMetadata(mnemonic, swapId, goldenVector),
        ).resolves.toEqual(samplePayload);
    });

    test("encodes the envelope as backend-compatible hex", async () => {
        const metadata = await encryptSwapMetadata(mnemonic, boundPayload);
        expect(metadata).toMatch(backendMetadataRegex);
        expect(metadata).toBe(metadata.toLowerCase());
    });

    test("produces a different ciphertext each time (random IV)", async () => {
        const first = await encryptSwapMetadata(mnemonic, boundPayload);
        const second = await encryptSwapMetadata(mnemonic, boundPayload);
        expect(first).not.toBe(second);
    });

    test("fails to decrypt with the wrong mnemonic", async () => {
        const metadata = await encryptSwapMetadata(mnemonic, boundPayload);
        await expect(
            decryptSwapMetadata(otherMnemonic, swapId, metadata),
        ).rejects.toBeDefined();
    });

    test("rejects metadata bound to a different swap", async () => {
        const metadata = await encryptSwapMetadata(mnemonic, boundPayload);
        await expect(
            decryptSwapMetadata(mnemonic, "other-swap", metadata),
        ).rejects.toThrow(/bound to a different swap/);
    });

    test("refuses to encrypt a lockup transaction without a swap binding", async () => {
        await expect(
            encryptSwapMetadata(mnemonic, samplePayload),
        ).rejects.toThrow(/must be bound to a swap/);
    });

    test("rejects a lockup transaction without a swap binding on decrypt", async () => {
        // Encryption of `{ lockupTx: "0xlockup" }` with `mnemonic` and no
        // swap binding. encryptSwapMetadata refuses to produce such a blob,
        // so this one was forged externally to prove decryption enforces the
        // invariant on its own instead of relying on writer discipline.
        const unboundLockupVector =
            "d28c50b5f8b24136ab8f0596947d882b8428eddbc4ab2174d4a9cbe33331a794" +
            "3f4745d9cdff939b8320b2399ce5d3e5bcf6ce";

        await expect(
            decryptSwapMetadata(mnemonic, swapId, unboundLockupVector),
        ).rejects.toThrow(/must be bound to a swap/);
    });

    test("rejects an envelope that is too short", async () => {
        const tooShort = hex.encode(new Uint8Array(12));
        await expect(
            decryptSwapMetadata(mnemonic, swapId, tooShort),
        ).rejects.toThrow(/too short/);
    });

    test("rejects unexpected payload fields", async () => {
        const metadata = await encryptSwapMetadata(mnemonic, {
            ...boundPayload,
            unexpected: true,
        } as never);

        await expect(
            decryptSwapMetadata(mnemonic, swapId, metadata),
        ).rejects.toThrow(/unknown field unexpected/);
    });

    test("rejects malformed DEX metadata", async () => {
        const metadata = await encryptSwapMetadata(mnemonic, {
            dex: {
                hops: [],
                position: SwapPosition.Post,
            },
        } as never);

        await expect(
            decryptSwapMetadata(mnemonic, swapId, metadata),
        ).rejects.toThrow(/quoteAmount/);
    });

    test("rejects malformed DEX hops", async () => {
        const metadata = await encryptSwapMetadata(mnemonic, {
            dex: {
                hops: [
                    {
                        type: SwapType.Dex,
                        from: "TBTC",
                        to: "USDT0",
                        unexpected: true,
                    },
                ],
                position: SwapPosition.Pre,
                quoteAmount: 1000,
            },
        } as never);

        await expect(
            decryptSwapMetadata(mnemonic, swapId, metadata),
        ).rejects.toThrow(/hops\[0\] contains unknown field unexpected/);
    });

    test("rejects malformed DEX hop details", async () => {
        const metadata = await encryptSwapMetadata(mnemonic, {
            dex: {
                hops: [
                    {
                        type: SwapType.Dex,
                        from: "TBTC",
                        to: "USDT0",
                        dexDetails: {
                            chain: "ARB",
                            tokenIn: 1,
                            tokenOut: "0xout",
                        },
                    },
                ],
                position: SwapPosition.Pre,
                quoteAmount: 1000,
            },
        } as never);

        await expect(
            decryptSwapMetadata(mnemonic, swapId, metadata),
        ).rejects.toThrow(/dexDetails\.tokenIn must be a string/);
    });
});

describe("buildSwapMetadataPayloadFromSwap", () => {
    test("can build metadata with only tx identity", () => {
        expect(
            buildSwapMetadataPayloadFromSwap({
                type: SwapType.Submarine,
                id: "swap-id",
                lockupTx: "0xtx",
            } as never),
        ).toEqual({ lockupTx: "0xtx" });
    });

    test("route metadata can be encrypted before lockup tx identity exists", async () => {
        const payload = buildSwapMetadataPayloadFromSwap({
            type: SwapType.Submarine,
            id: "swap-id",
            dex: {
                ...samplePayload.dex,
                unsupportedFutureField: true,
            },
            bridge: samplePayload.bridge,
        } as never);

        expect(payload).toEqual({
            dex: samplePayload.dex,
            bridge: samplePayload.bridge,
        });

        const metadata = await encryptSwapMetadata(mnemonic, payload!);
        await expect(
            decryptSwapMetadata(mnemonic, swapId, metadata),
        ).resolves.toEqual({
            dex: samplePayload.dex,
            bridge: samplePayload.bridge,
        });
    });

    test("does not add tx identity fields before a lockup transaction is known", () => {
        expect(
            buildSwapMetadataPayloadFromSwap({
                type: SwapType.Submarine,
                id: "swap-id",
                dex: {
                    ...samplePayload.dex,
                    unsupportedFutureField: true,
                },
                bridge: samplePayload.bridge,
            } as never),
        ).toEqual({
            dex: samplePayload.dex,
            bridge: samplePayload.bridge,
        });
    });
});

describe("patchEncryptedSwapMetadata", () => {
    beforeEach(() => {
        mocks.patchSwapMetadata.mockReset();
    });

    test("patches routed metadata bound to the swap id", async () => {
        await patchEncryptedSwapMetadata(
            {
                type: SwapType.Submarine,
                id: "swap-id",
                lockupTx: "0xtx",
                dex: samplePayload.dex,
            } as never,
            rescueFile,
        );

        expect(mocks.patchSwapMetadata).toHaveBeenCalledOnce();
        const [patchedSwapId, metadata] = mocks.patchSwapMetadata.mock.calls[0];
        expect(patchedSwapId).toBe("swap-id");
        await expect(
            decryptSwapMetadata(mnemonic, "swap-id", metadata),
        ).resolves.toEqual({
            lockupTx: "0xtx",
            dex: samplePayload.dex,
        });

        // The blob must not decrypt for any other swap.
        await expect(
            decryptSwapMetadata(mnemonic, "other-swap", metadata),
        ).rejects.toThrow(/bound to a different swap/);
    });

    test("does not patch tx identity without route metadata", async () => {
        await patchEncryptedSwapMetadata(
            {
                type: SwapType.Submarine,
                id: "swap-id",
                lockupTx: "0xtx",
            } as never,
            rescueFile,
        );

        expect(mocks.patchSwapMetadata).not.toHaveBeenCalled();
    });

    test("does not patch route metadata without tx identity", async () => {
        await patchEncryptedSwapMetadata(
            {
                type: SwapType.Submarine,
                id: "swap-id",
                dex: samplePayload.dex,
            } as never,
            rescueFile,
        );

        expect(mocks.patchSwapMetadata).not.toHaveBeenCalled();
    });
});
