import { hex } from "@scure/base";
import { BridgeKind, SwapPosition, SwapType } from "boltz-swaps/types";
import { beforeEach, vi } from "vitest";

import {
    type SwapMetadataPayload,
    buildSwapMetadataPayloadFromSwap,
    decryptSwapMetadata,
    encryptSwapMetadata,
    patchEncryptedSwapMetadata,
} from "../../src/utils/swapMetadata";

const mocks = vi.hoisted(() => ({
    patchSwapMetadata: vi.fn(),
}));

vi.mock("boltz-swaps/client", () => ({
    patchSwapMetadata: mocks.patchSwapMetadata,
}));

const mnemonic =
    "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about";
const otherMnemonic =
    "legal winner thank year wave sausage worth useful legal winner thank yellow";

// Matches the backend's metadata format (hex).
const backendMetadataRegex = /^(?:[0-9a-fA-F]{2})+$/;
const rescueFile = { mnemonic } as never;

const swapId = "swap-id";

const samplePayload: SwapMetadataPayload = {
    dex: {
        hops: [{ type: SwapType.Dex, from: "TBTC", to: "WBTC" }],
        position: SwapPosition.Post,
        quoteAmount: 12345,
    },
    lockupTx: "0xlockup",
    commitmentLockupTxHash: "0xcommitment",
    bridge: {
        sourceAsset: "USDC",
        destinationAsset: "USDC-BASE",
        kind: BridgeKind.Cctp,
        position: SwapPosition.Post,
    },
};

// Payloads carrying a lockup transaction must be bound to their swap.
const boundPayload = { ...samplePayload, swapId };

// Encryption of `boundPayload` with `mnemonic`, generated by the code this
// spec tests. Pins the wire format: HKDF salt/info, AES-GCM, IV length, the
// hex envelope and the payload schema (including the `version` tag). If this
// test breaks, every metadata blob already stored on the backend becomes
// undecryptable — never regenerate this vector to make a failing test pass;
// fix the code so old blobs keep decrypting.
const goldenVector =
    "74fd6f8b5b79cbcaa483580582b54ff4b5c91929c738e02afa72122feed26f0dc4ff914d" +
    "0dee94a7a27bd4acf68ab8718975310b5e2c3acfb8d2080c1f26dad34aae0f78e3645b8d" +
    "70f2356d098e10e7f8a2b018b4448f62fc2b49d3d80436710cf1bd8db6db33e3d5e69aa0" +
    "30259c85fe4026bcb52fee52f3bdf1ec0db808bb42c91a634608558739c28ae3b0e960d0" +
    "8e5c69d957194235429ae8a910a248187d7d7fb7e4fe43bc88f3a4b232b1bbf20c5f446f" +
    "bfdc548ac45feec9416be48a69b94c632bc039d2ba6be1a65fe4ecfd6fa68c5c1fd9a74d" +
    "b9a9cc3ce08c193ca061685d4641d12eddd6a0410847595b70ddbc0da59222758dc23164" +
    "c4b8aaaebe7c2ea14e0c64961da71ff6e15329835695a118f95db41d0d09b53e2c56e040" +
    "c8cea1eb8f6a3e2757d7b0b57997f14a805b55f3a400935e12";

// `boundPayload` encrypted in the pre-version format (no `version` tag). Frozen;
// do not regenerate unless `assertSupportedVersion` starts accepting such blobs.
const legacyVersionlessVector =
    "47e98dc81b988787e1bee38613eda55c3b34fe116dae7d70dc546c593e21f0817947eae8" +
    "04bf95e26e838aa1d6f2ca87052ecbb05702dad1337b6d0216d899d764a6c53650eda4a1" +
    "29c17263293f89f5522a0f92b461ad7aec127b2b3b9870b6213d99c6a190c3a7cd1b7f4b" +
    "ce970955241dce29540497cd0e2684703510bf97f6b8f7440b7cc21fc1e9b82a2bda5873" +
    "7a305e5f0d20879b5ff5d756bea144ff0037d54b0dcf1d8caa372e4d33a5b6d5b7fa39bb" +
    "c3ff0e779540983f637629d1d1044c012c764526dcc2823c7091011d265b6f38d6c8b31b" +
    "f94486829a310d088656b9c5261a81189f46b5bb3a6b04373cf652c12fe46e7766a42326" +
    "4a3641a61d2b77b728de8686f01f3f80515459433c9af3f3a54667e398e671c03ae43860" +
    "05e8827f0e1112727625ff94ac";

describe("swapMetadata crypto", () => {
    test("round-trips a payload through encrypt/decrypt", async () => {
        const metadata = await encryptSwapMetadata(mnemonic, boundPayload);
        expect(typeof metadata).toBe("string");

        const decrypted = await decryptSwapMetadata(mnemonic, swapId, metadata);
        expect(decrypted).toEqual(samplePayload);
    });

    test("decrypts the golden vector (wire format is frozen)", async () => {
        await expect(
            decryptSwapMetadata(mnemonic, swapId, goldenVector),
        ).resolves.toEqual(samplePayload);
    });

    test("rejects an unsupported (newer) metadata version", async () => {
        // Forged blob whose plaintext is `{ version: 2 }`. A reader that only
        // understands major 1 rejects it, so scan.ts falls back to on-chain
        // assets instead of mis-reading a future schema.
        const unsupportedVersionVector =
            "9c5207f7bf17b340fd69dc31f9930658ef97753b83ea9ded11813655c35e3b6c" +
            "c886e3cec1a5301423";

        await expect(
            decryptSwapMetadata(mnemonic, swapId, unsupportedVersionVector),
        ).rejects.toThrow(/unsupported swap metadata version/);
    });

    test("rejects a legacy version-less metadata blob", async () => {
        await expect(
            decryptSwapMetadata(mnemonic, swapId, legacyVersionlessVector),
        ).rejects.toThrow(/unsupported swap metadata version/);
    });

    test("encodes the envelope as backend-compatible hex", async () => {
        const metadata = await encryptSwapMetadata(mnemonic, boundPayload);
        expect(metadata).toMatch(backendMetadataRegex);
        expect(metadata).toBe(metadata.toLowerCase());
    });

    test("produces a different ciphertext each time (random IV)", async () => {
        const first = await encryptSwapMetadata(mnemonic, boundPayload);
        const second = await encryptSwapMetadata(mnemonic, boundPayload);
        expect(first).not.toBe(second);
    });

    test("fails to decrypt with the wrong mnemonic", async () => {
        const metadata = await encryptSwapMetadata(mnemonic, boundPayload);
        await expect(
            decryptSwapMetadata(otherMnemonic, swapId, metadata),
        ).rejects.toBeDefined();
    });

    test("rejects metadata bound to a different swap", async () => {
        const metadata = await encryptSwapMetadata(mnemonic, boundPayload);
        await expect(
            decryptSwapMetadata(mnemonic, "other-swap", metadata),
        ).rejects.toThrow(/bound to a different swap/);
    });

    test("refuses to encrypt a lockup transaction without a swap binding", async () => {
        await expect(
            encryptSwapMetadata(mnemonic, samplePayload),
        ).rejects.toThrow(/must be bound to a swap/);
    });

    test("rejects a lockup transaction without a swap binding on decrypt", async () => {
        // Encryption of `{ lockupTx: "0xlockup", version: 1 }` with `mnemonic`
        // and no swap binding. encryptSwapMetadata refuses to produce such a
        // blob, so this one was forged externally to prove decryption enforces
        // the invariant on its own instead of relying on writer discipline.
        const unboundLockupVector =
            "7a3d892b4aff04c6370e1be145899219c4240eb21376a1ed9bb0c1d051eb2938" +
            "b2d4a8ea0e670b993c7c919324df496f43efdc11cac4c53915c74ad61f5bb9";

        await expect(
            decryptSwapMetadata(mnemonic, swapId, unboundLockupVector),
        ).rejects.toThrow(/must be bound to a swap/);
    });

    test("rejects an envelope that is too short", async () => {
        const tooShort = hex.encode(new Uint8Array(12));
        await expect(
            decryptSwapMetadata(mnemonic, swapId, tooShort),
        ).rejects.toThrow(/too short/);
    });

    test("ignores unexpected payload fields (forward-compatible additive)", async () => {
        const metadata = await encryptSwapMetadata(mnemonic, {
            ...boundPayload,
            unexpected: true,
        } as never);

        await expect(
            decryptSwapMetadata(mnemonic, swapId, metadata),
        ).resolves.toEqual(samplePayload);
    });

    test("rejects malformed DEX metadata", async () => {
        const metadata = await encryptSwapMetadata(mnemonic, {
            dex: {
                hops: [],
                position: SwapPosition.Post,
            },
        } as never);

        await expect(
            decryptSwapMetadata(mnemonic, swapId, metadata),
        ).rejects.toThrow(/quoteAmount/);
    });

    test("ignores unexpected DEX hop fields (forward-compatible additive)", async () => {
        const metadata = await encryptSwapMetadata(mnemonic, {
            dex: {
                hops: [
                    {
                        type: SwapType.Dex,
                        from: "TBTC",
                        to: "USDT0",
                        unexpected: true,
                    },
                ],
                position: SwapPosition.Pre,
                quoteAmount: 1000,
            },
        } as never);

        await expect(
            decryptSwapMetadata(mnemonic, swapId, metadata),
        ).resolves.toEqual({
            dex: {
                hops: [{ type: SwapType.Dex, from: "TBTC", to: "USDT0" }],
                position: SwapPosition.Pre,
                quoteAmount: 1000,
            },
        });
    });

    test("rejects malformed DEX hop details", async () => {
        const metadata = await encryptSwapMetadata(mnemonic, {
            dex: {
                hops: [
                    {
                        type: SwapType.Dex,
                        from: "TBTC",
                        to: "USDT0",
                        dexDetails: {
                            chain: "ARB",
                            tokenIn: 1,
                            tokenOut: "0xout",
                        },
                    },
                ],
                position: SwapPosition.Pre,
                quoteAmount: 1000,
            },
        } as never);

        await expect(
            decryptSwapMetadata(mnemonic, swapId, metadata),
        ).rejects.toThrow(/dexDetails\.tokenIn must be a string/);
    });
});

describe("buildSwapMetadataPayloadFromSwap", () => {
    test("can build metadata with only tx identity", () => {
        expect(
            buildSwapMetadataPayloadFromSwap({
                type: SwapType.Submarine,
                id: "swap-id",
                lockupTx: "0xtx",
            } as never),
        ).toEqual({ lockupTx: "0xtx" });
    });

    test("route metadata can be encrypted before lockup tx identity exists", async () => {
        const payload = buildSwapMetadataPayloadFromSwap({
            type: SwapType.Submarine,
            id: "swap-id",
            dex: {
                ...samplePayload.dex,
                unsupportedFutureField: true,
            },
            bridge: samplePayload.bridge,
        } as never);

        expect(payload).toEqual({
            dex: samplePayload.dex,
            bridge: samplePayload.bridge,
        });

        const metadata = await encryptSwapMetadata(mnemonic, payload!);
        await expect(
            decryptSwapMetadata(mnemonic, swapId, metadata),
        ).resolves.toEqual({
            dex: samplePayload.dex,
            bridge: samplePayload.bridge,
        });
    });

    test("does not add tx identity fields before a lockup transaction is known", () => {
        expect(
            buildSwapMetadataPayloadFromSwap({
                type: SwapType.Submarine,
                id: "swap-id",
                dex: {
                    ...samplePayload.dex,
                    unsupportedFutureField: true,
                },
                bridge: samplePayload.bridge,
            } as never),
        ).toEqual({
            dex: samplePayload.dex,
            bridge: samplePayload.bridge,
        });
    });
});

describe("patchEncryptedSwapMetadata", () => {
    beforeEach(() => {
        mocks.patchSwapMetadata.mockReset();
    });

    test("patches routed metadata bound to the swap id", async () => {
        await patchEncryptedSwapMetadata(
            {
                type: SwapType.Submarine,
                id: "swap-id",
                lockupTx: "0xtx",
                dex: samplePayload.dex,
            } as never,
            rescueFile,
        );

        expect(mocks.patchSwapMetadata).toHaveBeenCalledOnce();
        const [patchedSwapId, metadata] = mocks.patchSwapMetadata.mock.calls[0];
        expect(patchedSwapId).toBe("swap-id");
        await expect(
            decryptSwapMetadata(mnemonic, "swap-id", metadata),
        ).resolves.toEqual({
            lockupTx: "0xtx",
            dex: samplePayload.dex,
        });

        // The blob must not decrypt for any other swap.
        await expect(
            decryptSwapMetadata(mnemonic, "other-swap", metadata),
        ).rejects.toThrow(/bound to a different swap/);
    });

    test("patches routed commitment metadata bound to the backend swap id", async () => {
        await patchEncryptedSwapMetadata(
            {
                type: SwapType.Submarine,
                id: "backend-swap-id",
                commitmentLockupTxHash: "0xcommitment",
                dex: samplePayload.dex,
                bridge: samplePayload.bridge,
            } as never,
            rescueFile,
        );

        expect(mocks.patchSwapMetadata).toHaveBeenCalledOnce();
        const [patchedSwapId, metadata] = mocks.patchSwapMetadata.mock.calls[0];
        expect(patchedSwapId).toBe("backend-swap-id");
        await expect(
            decryptSwapMetadata(mnemonic, "backend-swap-id", metadata),
        ).resolves.toEqual({
            commitmentLockupTxHash: "0xcommitment",
            dex: samplePayload.dex,
            bridge: samplePayload.bridge,
        });
    });

    test("does not patch tx identity without route metadata", async () => {
        await patchEncryptedSwapMetadata(
            {
                type: SwapType.Submarine,
                id: "swap-id",
                lockupTx: "0xtx",
            } as never,
            rescueFile,
        );

        expect(mocks.patchSwapMetadata).not.toHaveBeenCalled();
    });

    test("does not patch route metadata without tx identity", async () => {
        await patchEncryptedSwapMetadata(
            {
                type: SwapType.Submarine,
                id: "swap-id",
                dex: samplePayload.dex,
            } as never,
            rescueFile,
        );

        expect(mocks.patchSwapMetadata).not.toHaveBeenCalled();
    });
});
